/**
 * ANGULAR CONCEPT: Service
 * Services handle business logic and API communication
 * They are Injectable, meaning they can be used across components
 * 
 * This service manages all student-related HTTP requests
 */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Api_URL } from '../app.constants';
import { Student, StudentCreateRequest, StudentUpdateRequest } from '../models/student.model';

/**
 * ANGULAR CONCEPT: @Injectable decorator
 * Makes this service available for Dependency Injection
 * providedIn: 'root' means it's a singleton (one instance for entire app)
 */
@Injectable({
  providedIn: 'root'
})
export class StudentService {

  // Base URL for student endpoints
  private baseUrl = `${Api_URL}/admin/students`;

  /**
   * ANGULAR CONCEPT: Dependency Injection
   * HttpClient is injected via constructor
   * This allows us to make HTTP requests
   */
  constructor(private http: HttpClient) { }

  /**
   * Get all students with their assigned subjects
   * 
   * ANGULAR CONCEPT: Observable
   * Observables handle asynchronous data streams
   * Think of them as "promises with superpowers"
   * 
   * @returns Observable<Student[]> - Stream of student array
   */
  getAllStudents(): Observable<Student[]> {
    return this.http.get<Student[]>(this.baseUrl);
  }

  /**
   * Get single student by ID
   * @param id - Student database ID
   */
  getStudentById(id: number): Observable<Student> {
    return this.http.get<Student>(`${this.baseUrl}/${id}`);
  }

  /**
   * Create new student
   * 
   * @param request - Student data (name, username, password, etc.)
   * @returns Observable with success message
   */
  createStudent(request: StudentCreateRequest): Observable<any> {
    return this.http.post<any>(this.baseUrl, request);
  }

  /**
   * Update existing student
   * 
   * @param id - Student ID to update
   * @param request - Updated student data
   */
  updateStudent(id: number, request: StudentUpdateRequest): Observable<any> {
    return this.http.put<any>(`${this.baseUrl}/${id}`, request);
  }

  /**
   * Delete student
   * 
   * IMPORTANT: IDs are auto-generated by database
   * When you delete a student, their ID is gone forever
   * New students get the next available ID
   * 
   * @param id - Student ID to delete
   */
  deleteStudent(id: number): Observable<any> {
    return this.http.delete<any>(`${this.baseUrl}/${id}`);
  }

  /**
   * Assign subjects to student (max 5 subjects)
   * 
   * @param studentId - Which student
   * @param subjectIds - Array of subject IDs to assign
   */
  assignSubjects(studentId: number, subjectIds: number[]): Observable<any> {
    const request = {
      studentId: studentId,
      subjectIds: subjectIds
    };
    return this.http.post<any>(`${Api_URL}/admin/assign/student`, request);
  }

  /**
   * Remove a subject from student
   * 
   * @param studentId - Student ID
   * @param subjectId - Subject ID to remove
   */
  removeSubject(studentId: number, subjectId: number): Observable<any> {
    return this.http.delete<any>(
      `${Api_URL}/admin/assign/student/${studentId}/subject/${subjectId}`
    );
  }
}